/* Generated By:JavaCC: Do not edit this line. ParseError.java Version 0.6 */
package edu.cmu.cs.fluid.parse;

import edu.cmu.cs.fluid.*;

public class ParseError extends FluidException {
  public ParseError() { super(); }
  public ParseError(String s) { super(s); }
}
