package edu.cmu.cs.fluid.java.analysis;

import edu.cmu.cs.fluid.ir.IRNode;

public interface IAliasAnalysis {
  /**
   * Return true if the two expressions alias each other at the program point
   * indicated. This means they possibly evaluate to the same non-null
   * reference.
   * 
   * @param expr1
   *          a side-effect-free expression with correct binding information
   *          that would be legal at the execution point indicated. It need not
   *          be an expression in context.
   * @param expr2
   *          same as expr1
   * @param before
   *          indicates the execution point: just before evaluating this
   *          expression. <b>NB: we could instead write an interface using a
   *          ControlNode</b>
   */
  public boolean mayAlias(IRNode expr1, IRNode expr2, IRNode before);

  /**
   * As above, except that null is permitted (if both are null).
   */
  public boolean mustAlias(IRNode expr1, IRNode expr2, IRNode before);
  
  public Method getMayAliasMethod(IRNode before);
  
  public Method getMustAliasMethod(IRNode before);
  
  /**
   * Interface describing a method that abstracts the specific kind of 
   * alias analysis, may vs. must, being performed, and encapsulates the 
   * <em>location</em> in the code at which the alias comparison is
   * performed..  The intent is that
   * an implementation of this method invokes an implementation of 
   * either {@link IAliasAnalysis#mayAlias(IRNode, IRNode, IRNode)} or
   * {@link IAliasAnalysis#mustAlias(IRNode, IRNode, IRNode)}.
   * 
   * <p>Instances of this interface are generated by the methods
   * {@link IAliasAnalysis#getMustAliasMethod} and
   * {@link IAliasAnalysis#getMayAliasMethod}.
   */
  public interface Method {
    /**
     * Return true if the two expressions alias each other at the program point
     * indicated.
     * 
     * @param expr1
     *          a side-effect-free expression with correct binding information
     *          that would be legal at the execution point indicated. It need not
     *          be an expression in context.
     * @param expr2
     *          same as expr1
     */
    public boolean aliases(IRNode expr1, IRNode expr2);
  }
}
