/* $Header: /cvs/fluid/fluid/src/edu/cmu/cs/fluid/mvc/set/PureSet.java,v 1.17 2004/09/10 17:33:53 boyland Exp $
 *
 * PureSet.java
 * Created on February 28, 2002, 10:08 AM
 */

package edu.cmu.cs.fluid.mvc.set;

import edu.cmu.cs.fluid.ir.SlotAlreadyRegisteredException;
import edu.cmu.cs.fluid.ir.ExplicitSlotFactory;

/**
 * (Empty) specialization of {@link SetModel};
 * used as a more descriptive synonym.  Implementers should, for example, 
 * declared variables of this type rather than the parent type when using
 * models generated by {@link edu.cmu.cs.fluid.mvc.set.PureSet.Factory}.
 *
 * <P>An implementation must support the 
 * model-level attributes:
 * <ul>
 * <li>{@link edu.cmu.cs.fluid.mvc.Model#MODEL_NAME}
 * <li>{@link edu.cmu.cs.fluid.mvc.Model#MODEL_NODE}
 * <li>{@link SetModel#SIZE}
 * </ul>
 *
 * <P>An implementation must support the node-level
 * attributes:
 * <ul>
 * <li>{@link edu.cmu.cs.fluid.mvc.Model#IS_ELLIPSIS}
 * <li>{@link edu.cmu.cs.fluid.mvc.Model#ELLIDED_NODES}
 * </ul>
 *
 * @author Aaron Greenhouse
 */
public interface PureSet
extends SetModel
{ 
  /**
   * Interface for factories that create PureSet objects.
   * All PureSet model instances should be create through a factory
   * rather than through direct constructor calls.
   */
  public interface Factory
  {
    /**
     * Create a new Pure Set model.
     * @param name The name of the model.
     * @param sf The SlotFactory to use to create storage for the model's
     * structural attributes.
     */
    public PureSet create( String name, ExplicitSlotFactory sf )
    throws SlotAlreadyRegisteredException;
  }
}
