/*
 * PureSequence.java
 *
 * Created on March 1, 2002, 1:47 PM
 */

package edu.cmu.cs.fluid.mvc.sequence;

import edu.cmu.cs.fluid.ir.SlotAlreadyRegisteredException;
import edu.cmu.cs.fluid.ir.SlotFactory;

/**
 * (Empty) specialization of {@link SequenceModel};
 * used as a more descriptive synonym.  Implementers should, for example, 
 * declared variables of this type rather than the parent type when using
 * models generated by {@link edu.cmu.cs.fluid.mvc.sequence.PureSequence.Factory}.
 *
 * <P>An implementation must support the
 * model-level attributes:
 * <ul>
 * <li>{@link edu.cmu.cs.fluid.mvc.Model#MODEL_NAME}
 * <li>{@link edu.cmu.cs.fluid.mvc.Model#MODEL_NODE}
 * <li>{@link SequenceModel#SIZE}
 * <li>{@link SequenceModel#FIRST}
 * </ul>
 *
 * <P>An implementaiton must support the node-level
 * attributes:
 * <ul>
 * <li>{@link edu.cmu.cs.fluid.mvc.Model#IS_ELLIPSIS}
 * <li>{@link edu.cmu.cs.fluid.mvc.Model#ELLIDED_NODES}
 * <li>{@link #LOCATION}
 * <LI>{@link #INDEX}
 * <LI>{@link #NEXT}
 * <LI>{@link #PREVIOUS}
 * </ul>
 *
 * @author Aaron Greenhouse
 */
public interface PureSequence
extends SequenceModel
{
  /**
   * Interface for factories that create PureSequence objects.
   * All PureSequence model instances should be create through a factory
   * rather than through direct constructor calls.
   */
  public interface Factory
  {
    /**
     * Create a new PureSequence model instance.
     * @param name The name of the model.
     * @param sf The slot factory to use to create the model's
     *           structural attributes and the structure of the sequence itself.
     */
    public PureSequence create( String name, SlotFactory sf )
    throws SlotAlreadyRegisteredException;
  }
}
