/* $Header: /cvs/fluid/fluid/src/edu/cmu/cs/fluid/mvc/version/FixedVersionProjection.java,v 1.24 2003/07/15 18:39:11 thallora Exp $ */
package edu.cmu.cs.fluid.mvc.version;

import edu.cmu.cs.fluid.ir.SlotAlreadyRegisteredException;
import edu.cmu.cs.fluid.mvc.*;

/**
 * (Empty) specialization of {@link ModelAndVersionTrackerToModelStatefulView};
 * used as a more descriptive synonym.  Implementers should, for example, 
 * declared variables of this type rather than the parent type when using
 * models generated by {@link FixedVersionProjectionFactory}.
 *
 * <p>StatefulView of a single <code>Model</code> and 
 * a single <code>VersionTracker</code>.  Exports a <code>Model</code>
 * that is a projection of the source <code>Model</code> fixed at
 * the version referred to by the version cursor.
 *
 * <P>An implementation of this interface must support the 
 * model-level attributes:
 * <ul>
 * <li>{@link Model#MODEL_NAME}
 * <li>{@link Model#MODEL_NODE}
 * <li>{@link View#VIEW_NAME}
 * <li>{@link View#SRC_MODELS}
 * </ul>
 *
 * <p>The values of the MODEL_NAME and VIEW_NAME attributes do not
 * need to be the same.
 *
 * <P>An implementation must support the node-level
 * attributes:
 * <ul>
 * <li>{@link Model#IS_ELLIPSIS}
 * <li>{@link Model#ELLIDED_NODES}
 * </ul>
 *
 * @author Aaron Greenhouse
 */
public interface FixedVersionProjection
extends ModelAndVersionTrackerToModelStatefulView
{
  public static interface Factory
  {
    /**
     * Create a new fixed-version projection.  
     * @param name The name to give to the new model.
     * @param srcModel the versioned model to create a projection of.
     * @param tracker The version-cursor model that will control the version
     *               at which <code>srcModel</code> is projected.
     */
    public FixedVersionProjection create(
      String name, Model srcModel, VersionTrackerModel tracker )
    throws SlotAlreadyRegisteredException;
  }
}

